// Mechanical atlas padding and local WebP encoding. Artwork is generated by image_gen.
const fs=require("node:fs"),path=require("node:path"),sharp=require("sharp");
const root=path.resolve(__dirname,"../.."),out=path.join(root,"assets/intro/concept-live-v1");
const inputs=JSON.parse(fs.readFileSync(path.join(__dirname,"sources.json"),"utf8")).sources;
(async()=>{
  fs.mkdirSync(out,{recursive:true});
  const manifest={mode:"2.5D key-pose mesh animation",source:"approved cinematic concepts",profiles:{},arena:{
    desktop:[20/1850,76/850,1376/1850,750/850],mobile:[1414/1850,76/850,418/1850,750/850]
  },targetAnchor:[.494,.432],arrowTip:[.977,.465],durationMs:12000};
  for(const profile of ["desktop","mobile"]){
    const m=await sharp(inputs[profile]).metadata();
    if(m.width!==m.height||m.width%3)throw Error("Expected a square 3x3 pose atlas.");
    const sourceCell=m.width/3,margin=15,cell=sourceCell+margin*2,layers=[],offsets=[];
    for(let frame=0;frame<9;frame++){
      const input=await sharp(inputs[profile]).extract({left:frame%3*sourceCell,top:Math.floor(frame/3)*sourceCell,width:sourceCell,height:sourceCell}).png().toBuffer();
      const {data,info}=await sharp(input).ensureAlpha().raw().toBuffer({resolveWithObject:true});
      let bottom=0,pixels=0;for(let y=0;y<sourceCell;y++)for(let x=0;x<sourceCell;x++)if(data[(y*sourceCell+x)*4+3]>128){bottom=y;pixels++;}
      if(pixels<10000)throw Error("Empty pose "+frame);
      const dy=sourceCell-2-bottom;
      offsets.push([margin,margin+dy]);
      layers.push({input,left:frame%3*cell+margin,top:Math.floor(frame/3)*cell+margin+dy});
    }
    await sharp({create:{width:cell*3,height:cell*3,channels:4,background:"#00000000"}}).composite(layers).webp({quality:96,alphaQuality:100,effort:5}).toFile(path.join(out,"archer-"+profile+".webp"));
    manifest.profiles[profile]={cell,sourceCell,margin,offsets,frames:9};
  }
  for(const name of ["arena","target","arrow"])await sharp(inputs[name]).webp({quality:94,alphaQuality:100,effort:5}).toFile(path.join(out,name+".webp"));
  fs.writeFileSync(path.join(out,"manifest.json"),JSON.stringify(manifest,null,2)+"\n");
  console.log(JSON.stringify({directory:out,manifest}));
})().catch(e=>{console.error(e);process.exitCode=1;});

